Default: &defaults
  database: blog-website.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: blog-website_test.sqlite3
  <<: *defaults

Staging:
  database: blog-website_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: blog-website_production.sqlite3
  poolsize: 100
  <<: *defaults
